services:
  - type: web
    name: osint-email-scraper
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
